### ISSUE TITLE
erro "avcodec..."

### ISSUE THREAD

**Issue by FastOSlinux** [flathub/net.rpcs3.RPCS3#1]
Error in the game introduction. Worked on appimage version

sorry, I couldn't copy the text
![Captura de tela de 2020-07-13 18-05-18](https://user-images.githubusercontent.com/17401812/87353574-72e78180-c533-11ea-9a2c-3b46244e7397.png)

**Comment by Lctrs** [comment]
Out of the blue, could you try with org.freedesktop.Platform.ffmpeg-full installed ?

**Comment by FastOSlinux** [comment]
> Out of the blue, could you try with org.freedesktop.Platform.ffmpeg-full installed ?

yep 19.08

**Comment by Lctrs** [comment]
Could you attach RPCS3's log ? And give me the output of `$ flatpak list` ?

**Comment by FastOSlinux** [comment]
> Could you attach RPCS3's log ? And give me the output of `$ flatpak list` ?

[RPCS3.log](https://github.com/flathub/net.rpcs3.RPCS3/files/4927106/RPCS3.log)

flatpak list
https://paste.centos.org/view/81cfd536

**Comment by Lctrs** [comment]
Okay so it needs the MPEG2 video decoder, which will be part of `org.freedesktop.Platform.ffmpeg-full 20.08`. Will submit a patch to package it meanwhile later this week.

**Comment by Lctrs** [comment]
Could you test #2 ?

**Comment by FastOSlinux** [comment]
> Could you test #2 ?

is working!
