### ISSUE TITLE
Boot game - File browser frozen 

### ISSUE THREAD

**Issue by kolomansell** [flathub/net.rpcs3.RPCS3#10]
Hello,
File browser that appears with 'boot game' or  'add games' menu just freezes. I am able to resize window, but not click on any item or close it. 
Interesting thing is that browser from 'install packages' or 'install firmware' option works fine. It even looks different than the broken one. 

 I am suspecting it might be permission related issue as the file browser is showing my home folders, even if they should be invisible to the container. 
On the other hand the behavior does not change after allowing container home (or every) folder permissions.

Std out or logs don't give out any useful information.

`Debugger: 0
Icon theme "kfaenza-koko" not found.
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
sh: xdg-mime: command not found
`

I am running 0.0.13-1-eec11bfb version on Opensuse MircoOS - KDE desktop.

Thanks for help!

**Comment by Lctrs** [comment]
Please provide RPCS3's log.

To upload RPCS3's log, completely close RPCS3 then drag and drop RPCS3.log.gz from the emulator's folder into this page. It may have a zip or rar icon. Be sure to run the game before uploading the log.
On Flatpak it will be in `~/.var/app/net.rpcs3.RPCS3/.cache/rpcs3/`.
 
If RPCS3 crashed you'll have to look for the uncompressed log instead, named RPCS3.log. It can show up as just RPCS3 and have a notepad icon.

**Comment by Lctrs** [comment]
Out of curiosity, what happens if you run RPCS3 with `$ flatpak run --talk-name=org.freedesktop.FileManager1 net.rpcs3.RPCS3` ?

**Comment by Lctrs** [comment]
Plus, does this happen with the official AppImage ?

**Comment by kolomansell** [comment]
Hello,
Yes, the application has to be killed so there is not log file and the uncompressed one does not contain anything useful. I'll attach anyway. 
Appimage does not have this problem. it even opens another QT based file browser. I am attaching screenshots. 

I am starting to think this bug is not related to rpcs3 itself but to flaptak package on my dstribution. I have just found another application with the same problem. 

Appimage:
![appimage_screenshot](https://user-images.githubusercontent.com/49995902/103148358-1f729400-475f-11eb-9e02-7ad9999806dc.png)

Flatpak:
![flatpak_screen](https://user-images.githubusercontent.com/49995902/103148363-2c8f8300-475f-11eb-8ac4-1f063808572e.png)

RPCS3 log:
[RPCS3.log](https://github.com/flathub/net.rpcs3.RPCS3/files/5742862/RPCS3.log)

**Comment by Lctrs** [comment]
Yeah. Might be worth having a look in your distribution's bugtracker to see if something like this has been already reported.
