### ISSUE TITLE
Crash when using a symlink for the configuration

### ISSUE THREAD

**Issue by dragonDScript** [flathub/net.rpcs3.RPCS3#1006]
When trying to use a symlink instead of a folder, at `~/.var/app/net.rpcs3.RPCS3/config/rpcs3`, RPCS3 unexpectedly crashes when clicking the config. It doesn't load any game or custom theme.
![imagen](https://user-images.githubusercontent.com/46191980/173235069-a4fd4a8f-ed9b-4f94-b815-e3181f251880.png)

**Comment by Lctrs** [comment]
I guess that the flatpak doesn't have access to the target directory ?

**Comment by dragonDScript** [comment]
That makes sense. Let me change some permissions on Flatseal

**Comment by dragonDScript** [comment]
Solved
