### ISSUE TITLE
Question: rpcs3-llvm vs flatpak's llvm

### ISSUE THREAD

**Issue by XargonWan** [flathub/net.rpcs3.RPCS3#1010]
Greetings,

I'm wondering: is there any specific reason why youŕe compiling your own llvm instead using the one bundled with flatpak?
If so, would the bundled one work correctly?

Thanks in advance.

**Comment by Lctrs** [comment]
rpcs3-llvm is a special fork of LLVM by rpcs3's team with specific patches for RPCS3 that can't be applied upstream.
