### ISSUE TITLE
Can't open File Manager

### ISSUE THREAD

**Issue by CarlBraun** [flathub/net.rpcs3.RPCS3#1015]
Your File Manager is frozen after using "Add Games" feature. Check it out, need an update or replacement. No way to Add Games anymore...

**Comment by Lctrs** [comment]
Do you reproduce the issue with the official appimage ?

Do you have a log file ?

**Comment by CarlBraun** [comment]
Give me any guide or idea please

**Comment by CarlBraun** [comment]
Last update in Flatpak store fixes issue.
