### ISSUE TITLE
Restore auto-merge update PR

### ISSUE THREAD

**Issue by Lctrs** [flathub/net.rpcs3.RPCS3#1235]
Following #1224 

ping @j8r. If you have any idea...

**Comment by j8r** [comment]
You have to wait to the next midnight to have the PR merged automatically.
The GitHub Action runs each day at 0:00, which will merge the existing PR and create a new one if a new release has been created since then.

**Comment by Lctrs** [comment]
That will not work.

If the master branch is not at the specified commit, the build will fail. And a lot of commits can be merged into master in 24 hours on upstream side...

**Comment by j8r** [comment]
Not sure if the whole build is done all over again when a PR is merged automatically.
We'll see.

**Comment by j8r** [comment]
We can do a `sed` to update the commit in the GitHub Action, and comment the `branch` field.
Before that I'd like to see the error, so we could eventually show it to others.

**Comment by Lctrs** [comment]
Or we can just run it again at 1am to have the auto merge soon enough...

**Comment by j8r** [comment]
No ideal, a commit may be pushed in this time span eventually.

**Comment by Lctrs** [comment]
Still better than a 24 hours span. It was good enough when we ran on the normal workflow.

**Comment by barthalion** [comment]
As I said elsewhere, I'll accept a linter exception allowing a "commitless" branch if you submit a PR.

**Comment by barthalion** [comment]
Then you can have an action at midnight, and another one e.g. 2 hours later that will merge such PR automatically, or just stick to f-e-d-c.

**Comment by Lctrs** [comment]
@barthalion The issue in https://github.com/flathub/flatpak-builder-lint/issues/30 was not about https://github.com/RPCS3/rpcs3.git source but about https://github.com/intel/ittapi.git one. I haven't had the time to submit the exception yet but it's on my todo list.

**Comment by barthalion** [comment]
Sure, I'm just pointing out f-e-d-c can do automerges: https://github.com/flathub/flatpak-external-data-checker/#automatically-merging-prs

**Comment by Lctrs** [comment]
Yeah I know that. That's what we used before switching to a custom workflow for fedc.

I just realized that with the current workflow implementation, it takes 24 hours for a PR to be auto merged, which is way too long. So we'll just make it run twice per day on a shorter period.

**Comment by j8r** [comment]
I don't think it is too long, there is no hurry. Even the AUR don't update that often.
PCSX2 is updated once a week.

**Comment by Lctrs** [comment]
It's too long because they will likely make new commits in master in 24 hours and so our build after the merging will fail.

**Comment by j8r** [comment]
Yes at any rate the PR should be merged quickly after success.

**Comment by j8r** [comment]
What I was afraid happened: a new commit can be created between each run, even if they are close enough.
Maybe just --edit-only will do in the second run?

**Comment by Lctrs** [comment]
@j8r There was no new commit created between each run.

If you look at the creation date of the 2 last MRs, you'll see that they have been created on 2 different days. So this side is okay, what is not is that the second run is never triggered on GHA side.

Why that ? From what I deducted, when you specify a cron for a github actions, it will not run automatically at specified cron time, but rather pushed in a queue to be treated later, which makes sense on GHA side. But it appears other runs will not be queued if a run is already queued. That's why we have run times around 1:30am currently.

**Comment by j8r** [comment]
Ok, but this can still happen - an will eventually.
Then a solution for the issue you described should be to create to worklows, then it should be ok from my understanding.

**Comment by j8r** [comment]
Ok, thanks. However this can still happen - and will eventually.
Then a solution for the issue you described should be to create two worklows, then it should be ok from my understanding.

**Comment by Lctrs** [comment]
Yes. It will resolve both issues.

**Comment by j8r** [comment]
What's strange on this case is it was supposed to work: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule.

There is a note though:
```
Note: The schedule event can be delayed during periods of high loads of GitHub Actions workflow runs.
High load times include the start of every hour.
To decrease the chance of delay, schedule your workflow to run at a different time of the hour.
```

For the two workflows, what remains will be a possibility that the linter fails when pushed on master, but that's fine, the project being updated regularly.

**Comment by Lctrs** [comment]
@j8r Auto merge doesn't work with `--edit-only` argument.
