### ISSUE TITLE
Emulator immediately crashing on launch

### ISSUE THREAD

**Issue by StinkoBrown** [flathub/net.rpcs3.RPCS3#1398]
This is my first time writing a GitHub issue so apologies if this isn't done in the correct way.

RPCS3 is crashing immediately after opening it. This was not happening yesterday and only started today. Only the flatpak seems to have this issue as the Appimage is working fine. I tested this on the Steam Deck and several other people on the Discovery page can confirm this issue. Installing it through Emudeck or Discovery seems to make no difference.

Don't know if it helps or not, but here is a link to my RPCS3 log file, though I can't make heads or tails of its contents: https://we.tl/t-9H5VYrljsB

**Comment by rivenirvana** [comment]
May be related, latest build has not been launching for me as well.
journalctl logs `net.rpcs3.RPCS3.desktop[105932]: rpcs3: error while loading shared libraries: libLLVM-16.so: cannot open shared object file: No such file or directory`
