### ISSUE TITLE
flathub verification?

### ISSUE THREAD

**Issue by RoyalOughtness** [flathub/net.rpcs3.RPCS3#1607]
Getting verification would allow an increased level of user trust.

https://discourse.flathub.org/t/how-do-you-get-a-flathub-submission-verified/3714
https://flathub.org/apps/collection/verified/1

I believe this would require the blessing of upstream devs via hosting a file.

**Comment by Lctrs** [comment]
Upstream have showed numerous times that they have no interest in supporting a flatpak build. So won't happen I guess.

**Comment by j8r** [comment]
Closing the issue, it won't happen anytime soon - nothing we can do about it.
