### ISSUE TITLE
RPCS3 won't boot - symbol lookup error

### ISSUE THREAD

**Issue by rawdatafeel** [flathub/net.rpcs3.RPCS3#1632]
![image](https://github.com/flathub/net.rpcs3.RPCS3/assets/108900299/97ca2a01-8115-4b92-a86b-eb6aeb925937)

Citra and Dolphin have the same issue.

Citra fix is here: https://github.com/flathub/org.citra_emu.citra/issues/658#issuecomment-1975327574

**Comment by Lctrs** [comment]
I've triggered a [manual build](https://buildbot.flathub.org/#/builders/6/builds/104676). Should be available in a couple hours.
