### ISSUE TITLE
Messed up interface

### ISSUE THREAD

**Issue by Mek101** [flathub/net.rpcs3.RPCS3#164]
I'm not sure this is strictly a flatpak issue, however it could be related to the absence of QT themeing on Linux Mint 20.1 Cinnamon

![Schermata del 2021-04-11 23-24-55](https://user-images.githubusercontent.com/34246799/114321894-9ae52f00-9b1d-11eb-9138-8178495f16dd.png)

**Comment by Lctrs** [comment]
Can you reproduce it with the official appimage ? If you change RPCS3's theme, does it change anything ?

Do you have any of the `org.gtk.Gtk3theme.Mint-Y(*)` flatpak installed ? If no, try to install one of them.

**Comment by Mek101** [comment]
I was using the Mint Y Pink theme. I'm not on mint anymore, so I will try and test both the flarpak and appimage on manjaro to see if it persists

**Comment by Mek101** [comment]
I was using the Mint Y Pink theme. Currently I'm not on mint anymore, but Manjaro Gnome (I did a complete reinstall due to unrelated bugs), and the issue persist with both the flatpak installation and the appimage

**Comment by Lctrs** [comment]
If you can reproduce the issue with the appimage, your bug has nothing to do with flatpak, but rather with your distribution.

You can have a look at this [page](https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications) to try to resolve it.
