### ISSUE TITLE
Please remove usages of branch property from manifests

### ISSUE THREAD

**Issue by bbhtt** [flathub/net.rpcs3.RPCS3#1679]
https://github.com/flathub/net.rpcs3.RPCS3/blob/5d1bfdeb2df279f22304888c7e896cc6f51f3661/net.rpcs3.RPCS3.yaml#L90

should be tag or commit or tag+commit

**Comment by Lctrs** [comment]
Can't. RPCS3 is a rolling release software and we want to be always on top of the master branch.

**Comment by bbhtt** [comment]
Flathub is not for nightlies to update on every commit. Use the tags, branch is blocked in the linter.

**Comment by j8r** [comment]
I guess we can use that: https://github.com/RPCS3/rpcs3/releases.
Some projects prefer rolling-releases, which seems to fit them well - like Flycast.
If the developers and users are happy, that's the most important.

**Comment by j8r** [comment]
By the way @bbhtt, thank you to have warned us - I'll make a PR. However, that's not really us packagers to convince to change upstream development model, we just deal with what we are given :slightly_smiling_face:

**Comment by j8r** [comment]
@Lctrs I see two options:
- we move from the "git" to the "archive" source and still use FEDC, because from what I see at https://github.com/flathub-infra/flatpak-external-data-checker a git source needs a tag.
- or, we use a GitHub Actions cron to update each day to the latest commit by pushing to master (not sure if it still work)

**Comment by Lctrs** [comment]
@bbhtt that's why we use a custom github actions to run fedc once a day, to not overflow the flathub's build infra on every upstream commit.

@j8r seems like github's archive source does not include git submodules, which only left us with the second option.

**Comment by bbhtt** [comment]
> @bbhtt that's why we use a custom github actions to run fedc once a day, to not overflow the flathub's build infra on every upstream commit.

That does not help, the build still happens on the infra just multiple times a day.

**Comment by bbhtt** [comment]
Ok seems I misunderstood the setup here, updating once per day is fine. I'll add an exception to for this.

Please don't try to increase the frequency of the action.

**Comment by bbhtt** [comment]
Added an exception. Restart the build in a couple of hours.

Note that it doesn't solve the main issue of branch and commit in the manifest going out of sync and the build from the merge commit silently failing and the update failing to deploy.

The linter won't be able to catch that because of the exception. I assume this is fine, since you really want to update on each commit.
