### ISSUE TITLE
game .desktop does not work

### ISSUE THREAD

**Issue by B-Nerd** [flathub/net.rpcs3.RPCS3#1746]
when i create a .desktop it does not work that is because where the is in the .desktop file is wrong it is not here Exec="/app/bin/rpcs3" but here Exec="/var/lib/flatpak/exports/bin/net.rpcs3.RPCS3

**Comment by j8r** [comment]
Duplicate of https://github.com/flathub/net.rpcs3.RPCS3/issues/1449 ? If yes, can be closed to centralize the issue.

**Comment by B-Nerd** [comment]
> Duplicate of #1449 ? If yes, can be closed to centralize the issue.

yep misread that one
