### ISSUE TITLE
Request: Add StartupWMClass=rpcs3 to net.rpcs3.RPCS3.desktop file

### ISSUE THREAD

**Issue by GiantEnemyCrab** [flathub/net.rpcs3.RPCS3#444]
In Budgie Desktop Environment, in order to pin application to Icon Task List dock, I think it depends on `.desktop` file having `StartupWMClass` being present. (Reference: https://github.com/solus-project/budgie-desktop/issues/750)

I experimented with changing the .desktop file directly in `/var/lib/flatpak/exports/share/applications/net.rpcs3.RPCS3.desktop` and it worked very well. With `StartupWMClass=rpcs3` added, it looks like below (just that one line was added):
```
[Desktop Entry]
Type=Application
Name=RPCS3
GenericName=PlayStation 3 Emulator
Comment=An open-source PlayStation 3 emulator/debugger written in C++.
Icon=net.rpcs3.RPCS3
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=rpcs3 --file-forwarding net.rpcs3.RPCS3 @@ %f @@
Terminal=false
Categories=Game;Emulator;
Keywords=PS3;Playstation;
StartupWMClass=rpcs3
X-Flatpak-RenamedFrom=rpcs3.desktop;
X-Flatpak=net.rpcs3.RPCS3
```

I was seeing something like [yuzu flatpak desktop-file-edit command](https://github.com/flathub/org.yuzu_emu.yuzu/blob/bef7dd1a234120398f991089abf5cc69c3a05b13/org.yuzu_emu.yuzu.json#L204), which could be additional reference.

**Comment by Lctrs** [comment]
You should submit this [upstream](https://github.com/RPCS3/rpcs3.git).

**Comment by GiantEnemyCrab** [comment]
Submitted to https://github.com/RPCS3/rpcs3/issues/10685

**Comment by GiantEnemyCrab** [comment]
@Lctrs Upstream rpcs3 has been able to merge this request, so it should be all set.
