### ISSUE TITLE
org.freedesktop.ScreenSaver and org.mate.ScreenSaver not exposed for screen saver inhibition

### ISSUE THREAD

**Issue by dariox86** [flathub/net.rpcs3.RPCS3#611]
«Prevent display sleep while running games» is greyed out in RPCS3 because org.freedesktop.ScreenSaver is not exposed. In my case I use MATE desktop environment, so I issued: `$ flatpak --user override --talk-name=org.mate.ScreenSaver net.rpcs3.RPCS3` to fix the issue. From looking [at this](https://github.com/RPCS3/rpcs3/blob/master/rpcs3/display_sleep_control.cpp) it seems org.freedesktop.ScreenSaver and org.mate.ScreenSaver should be exposed.

**Comment by Lctrs** [comment]
PR welcome :)
