### ISSUE TITLE
libusb regression causes crash during emulator context destruction

### ISSUE THREAD

**Issue by dogtopus** [flathub/net.rpcs3.RPCS3#808]
Due to libusb/libusb#1079, the emulator context sometimes cannot properly quit and will crash the whole program. This apparently includes PS3 firmware installation so it would look like that the firmware installation failed, with nothing useful leaving in the logs other than a crash message that looked like null pointer dereferencing.

The official AppImage build isn't affected by this currently.

Looks like libusb is going to have a bugfix release by the end of March. Meanwhile a hotfix would be (temporarily) switching to master branch of libusb.

**Comment by Lctrs** [comment]
Thank you for finding this. Will revert to 1.0.24 instead.
